language: php

matrix:
  include:
    - php: 5.6
      env: TESTS=1
    - php: 7.0
      env: TESTS=1
    - php: 7.1
      env: TESTS=1 PHPCS=1
    - php: 7.2
      env: COVERAGE=1

before_script:
  - composer install --prefer-dist

script:
  - if [[ $TESTS ]]; then vendor/bin/phpunit; fi
  - if [[ $COVERAGE ]]; then vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS ]]; then vendor/bin/phpcs --standard=PSR2 src/ tests/; fi

after_success:
  - if [[ $COVERAGE ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
